# Generated by Django 4.1.2 on 2022-12-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=25)),
                ('numero_cliente', models.TextField(max_length=50)),
                ('fecha_registro', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=60)),
                ('apellido_m', models.CharField(max_length=60)),
                ('nombre', models.TextField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codproducto', models.CharField(max_length=50)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('provedor', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('cantidad_x_unidad', models.CharField(max_length=50)),
                ('valor_peso', models.CharField(max_length=50)),
                ('valor_euro', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleta', models.CharField(max_length=50)),
                ('Producto', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=50)),
                ('venta_bruto', models.CharField(max_length=50)),
                ('iva', models.CharField(max_length=50)),
                ('total_venta', models.CharField(max_length=50)),
            ],
        ),
    ]
